name: Flickerstrip
titletagline: Bring your creativity to light
companyname: Reflowster
markdown: redcarpet
kickstarterurl: https://www.flickerstrip.com
highlighter: pygments
exclude: [tasks, README.md]
include: [.htaccess]
url: http://flickerstrip.com
gems: ["jekyll-sitemap","jekyll-less"]
excerpt_separator: <!--more-->
authors:
  julian:
    display_name: Julian Hartline
    gravatar: 300aa4fabf894a18d740058bbcad03e6
    email: julianh2o@gmail.com
    web: http://www.julianhartline.com/
    twitter: reflowster
    github: julianh2o
